# Generated by Django 4.1.6 on 2023-03-30 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_me', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='commoner', to='tutor_me.customuser'),
        ),
        migrations.AlterField(
            model_name='session',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='tutor_me.customuser'),
        ),
    ]
