# Generated by Django 4.1.6 on 2023-04-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_me', '0008_alter_customuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(null=True, upload_to='media/Tutor Me/static/tutor_me/images/uploads/'),
        ),
    ]
