# Generated by Django 4.1.5 on 2023-04-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_me', '0012_alter_customuser_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(default='Tutor Me/static/tutor_me/images/uploads/default.jpg', upload_to='Tutor Me/static/tutor_me/images/uploads/'),
        ),
    ]
