# Generated by Django 4.1.6 on 2023-04-18 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_me', '0013_alter_customuser_picture'),
        ('tutor_me', '0013_notification'),
    ]

    operations = [
    ]
