# Generated by Django 4.1.5 on 2023-04-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_me', '0014_merge_0013_alter_customuser_picture_0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='major',
            field=models.TextField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_num',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='year',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
