# Generated by Django 4.1.5 on 2023-04-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_me', '0015_customuser_major_customuser_phone_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sm_platform',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='social_media',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
