# Generated by Django 4.1.5 on 2023-04-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_me', '0016_customuser_sm_platform_alter_customuser_social_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='major',
            field=models.TextField(default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_num',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sm_platform',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='social_media',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='year',
            field=models.TextField(default='', max_length=100),
        ),
    ]
