# Generated by Django 4.1.6 on 2023-05-03 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_me', '0020_notification_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 0, 16, 48, 218518, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
