"""
Django settings for TutorMeA15 project.

Generated by 'django-admin startproject' using Django 4.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import sys
import django_heroku
import dj_database_url
import os
import mimetypes

MIME_TYPES = (
    ('text/css', '.css'),
)

SECURE_CONTENT_TYPE_NOSNIFF = True

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*uf6aybr)g5p7@9rwzr!kstjszblg&45_oirv67^pi*tke7*+m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False  # security update - removed, breaks profile page

# ALLOWED_HOSTS = ['*'] # security update

ALLOWED_HOSTS = ['tutor-me-a15.herokuapp.com/', 'tutor-me-a15.herokuapp.com',
                 'https://tutor-me-a15.herokuapp.com', '127.0.0.1', 'localhost']  # security update - works

#CSRF_COOKIE_SECURE = True  # security update - works
# SESSION_COOKIE_SECURE = True  # security update that broke Django CI
#SECURE_HSTS_SECONDS = 3600  # security update - works
#SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # security update - works
#SECURE_SSL_HOST = 'tutor-me-a15.herokuapp.com'  # security update - works
#SECURE_SSL_HOST = 'https://tutor-me-a15.herokuapp.com' # updated link to include HTTPS
#SECURE_SSL_REDIRECT = False  # security update that broke Django CI
#SECURE_BROWSER_XSS_Filter = True  # security update - works
#X_FRAME_OPTIONS = 'SAMEORIGIN'  # security update - works

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_heroku',
    'django.contrib.sites',
    'tutor_me',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'crispy_forms',
    'bootstrap5',
    'django.contrib.postgres'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'TutorMeA15.urls'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
            ],
        },
    },
]

WSGI_APPLICATION = 'TutorMeA15.wsgi.application'

#USE_TZ = True
TIME_ZONE = "America/New_York"

#Database
#https://docs.djangoproject.com/en/4.1/ref/settings/#databases
if 'test' in sys.argv:
    DATABASES = {
        'default':{
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': 'mydatabase'
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'dco271qmmgj7o5',
            'USER': 'zcwnyfmvuumhdo',
            'PASSWORD': 'a8ca157f34fb21ebfc0c1dc467e65ae4b1da1472888ee3fd38788d76801358c6',
            'HOST': 'ec2-18-215-96-22.compute-1.amazonaws.com',
            'PORT': '5432',
            # 'TEST': {
            #     'NAME': 'postgres',
            # },
        }
    }

import dj_database_url
db_from_env = dj_database_url.config(conn_max_age=600)
DATABASES['default'].update(db_from_env)


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# STATIC_URL = 'static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)


STATIC_URL = 'Tutor Me/static/tutor_me/images/uploads/'
STATIC_ROOT = BASE_DIR / "staticfiles"
#STATICFILES_DIRS = [
#    os.path.join(BASE_DIR, "static")
#]
STATICFILES_DIRS = [os.path.join(BASE_DIR, ""),
                    os.path.join(BASE_DIR, "static"),
                    os.path.join(BASE_DIR), "Tutor Me/static/tutor_me/images/uploads/"]

#MEDIA_URL = 'media/'
#MEDIA_ROOT = os.path.join(BASE_DIR, MEDIA_URL)


STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# STATICFILES_STORAGE = 'whitenoise.django.GzipManifestStaticFilesStorage'
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
#django_heroku.settings(locals())

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend'
]

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

SITE_ID = 3

LOGIN_REDIRECT_URL = '/direct'
LOGOUT_REDIRECT_URL = '/'
SOCIALACCOUNT_LOGIN_ON_GET = True
ACCOUNT_LOGOUT_ON_GET = True
